package com.teknasyon.desk360.modelv2

data class Desk360ScreenTicketDetail(
    val title: String = "Destek Taleplerim",
    val button_text: String = "Yeni Talep Ekle",
    val chat_box_style: Int = 1,
    val button_style_id: Int = 1,
    val button_text_color: String = "#FFFFFF",
    val button_border_color: String = "#58B0FA",
    val button_icon_is_hidden: Boolean = false,
    val button_text_font_size: Int = 18,
    val chat_background_color: String = "#EEEFF0",
    val chat_sender_font_size: Int = 16,
    val chat_sender_date_color: String = "#9298B1",
    val chat_sender_text_color: String = "#FFFFFF",
    val button_background_color: String = "#58B0FA",
    val button_shadow_is_hidden: Boolean = false,
    val button_text_font_weight: Int = 600,
    val chat_receiver_font_size: Int = 16,
    val chat_sender_font_weight: Int = 400,
    val write_message_font_size: Int = 16,
    val chat_receiver_date_color: String = "#9298B1",
    val chat_receiver_text_color: String = "#525A7E",
    val write_message_text_color: String = "#9298B1",
    val chat_receiver_font_weight: Int = 400,
    val write_message_font_weight: Int = 400,
    val write_message_border_color: String = "#C2C7CC",
    val chat_sender_background_color: String = "#66748B",
    val chat_sender_shadow_is_hidden: Boolean = false,
    val chat_receiver_background_color: String = "#FFFFFF",
    val chat_receiver_shadow_is_hidden: Boolean = false,
    val write_message_background_color: String = "#FFFFFF",
    val write_message_button_icon_color: String = "#58B0FA",
    val write_message_place_holder_text: String = "Mesaj Yaz",
    val write_message_place_holder_color: String = "#9298B1",
    val write_message_border_active_color: String = "#000000",
    val write_message_button_background_color: String = "#ffffff",
    val write_message_button_background_disable_color: String = "#ffffff",
    val write_message_button_icon_disable_color: String = "#D0D0D0"
)